version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: d8
      MYSQL_USER: d8
      MYSQL_PASSWORD: d8
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql
#      - ./docker-runtime/mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here

  php:
    image: wodby/drupal-php:7.0 # Allowed: 7.0, 5.6.
    volumes:
      - ../drupal8:/var/www/html

  nginx:
    image: wodby/drupal-nginx
    environment:
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
      NGINX_UPSTREAM_NAME: php
    volumes_from:
      - php

#  redis:
#    image: redis:3.2-alpine
#
#  memcached:
#    image: memcached:1.4-alpine
#
#  solr:
#    image: solr:5.5-alpine
#    volumes:
#      - ./docker-runtime/solr:/opt/solr/server/solr/mycores
#    ports:
#      - "8003:8983"
